# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Institute of Social Emotional Education
# description: > # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
#
baseurl: "https://me-you-us.org" # the subpath of your site, e.g. /blog
url: "https://me-you-us.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme:
plugins: []

tr:
  en:
    home:
      name: "Home"
      url: "/"
    mission:
      name: "Our mission & vision"
      url: "/our-mission.html"
    offer:
      name: "What we offer"
      url: "/what-we-offer.html"
    experience:
      name: "Our experience"
      url: "/our-experience.html"
    about:
      name: "About us"
      url: "/about-us.html"
    news:
      name: "News and events"
      url: "/news-and-events.html"
    # contact:
    #   name: "Contact us"
    #   url: "/contact-us.html"
  fr:
    home:
      name: "Accueil"
      url: "/"
    mission:
      name: "Notre mission"
      url: "/notre-mission/"
    offer:
      name: "What we offer fr"
      url: "/what-we-offer-fr/"
    experience:
      name: "Notre experience"
      url: "/notre-experience/"
    about:
      name: "À propos"
      url: "/a-propos/"
    news:
      name: "Nouvelles"
      url: "/nouvelles/"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
